

INSERT INTO CITY
(ID , NAME)
VALUES
(1 , 'WARANGAL');


INSERT INTO REFEREE
(ID , NAME)
VALUES
(1 , 'RAMESH');


INSERT INTO INNINGS
(ID , INNINGS_NUMBER)
VALUES
(1 , 2);


INSERT INTO EXTRA_TYPE
(ID , NAME)
VALUES
(1, 'CHARITH');


INSERT INTO SKILL
(ID , NAME)
VALUES
(1, 'RAIDER');


INSERT INTO TEAM
(ID , NAME , COACH , HOME_CITY , CAPTAIN)
VALUES
(1, 'TELUGU TITANS' , 'MR.CHAKRI' , 1 , 1);


INSERT INTO PLAYER
(ID , NAME , COUNTRY , SKILL_ID , TEAM_ID)
VALUES
(1 , 'GIRISH' , 'INDIA' , 1 , 1);


INSERT INTO VENUE
(ID , STADIUM_NAME , CITY_ID)
VALUES
(1 , 'J.N.S INDOOR STADIUM' , 1);


INSERT INTO EVENT
(ID , INNINGS_ID , EVENT_NO , RAIDER_ID , RAID_POINTS , DEFENDING_POINTS , CLOCK_IN_SECONDS , TEAM_ONE_SCORE , TEAM_TWO_SCORE)
VALUES
(1 , 2 , 1 , 1 , 10 , 6 , 30 , 16 , 10 );


INSERT INTO EXTRA_EVENT
(ID , EVENT_ID , EXTRA_TYPE_ID , POINTS , SCORING_TEAM_ID)
VALUES
( 1, 1 , 1 , 16 , 1);


INSERT INTO OUTCOME
(ID , STATUS , WINNER_TEAM_ID , SCORE , PLAYER_OF_MATCH)
VALUES
(1 , 'COMPLETED' , 1 , 18 , 2);

--12. Insert into game



UPDATE PLAYER 
SET SKILL_ID = 2
WHERE COUNTRY = 'INDIA';


UPDATE PLAYER
SET NAME = ' CHOUDHARY'
WHERE TEAM_ID = 1;

--15. Update player table

--16. Update player table


DELETE FROM EXTRA_TYPE WHERE ID =1 ;

--18. Delete from referee
DELETE FROM REFEREE WHERE ID = 1;

--19. Delete from player
DELETE FROM PLAYER WHERE TEAM_ID = 1;

--20. Delete from outcome
DELETE FROM OUTCOME WHERE STATUS = 'COMPLETED';